### ISSUE TITLE
createRequests API doesn't match createActionsAPI

### ISSUE THREAD

**Issue by jkosoy** [eugene-manuilov/redux-wordpress#6]
Looks like `createRequests` is supposed to be

```
export default function createRequests(name, host, endpoints, args = {})
```

And subsequently account for the namespace appropriately. As it sits if you follow the tutorial on the README you get

```
TypeError: endpoints.forEach is not a function
```

as endpoints is one argument off.

**Comment by eugene-manuilov** [comment]
Hi @jkosoy!

sorry, there is a bug in the example. It should be like this:

```
// actionCreators.js

import { createRequests } from 'redux-wordpress';

const requests = createRequests('http://mysite.test/wp-json/', ['books', 'authors']);

export function fetchInitialData() {
    return dispatch => {
        return Promise
            .all([
                requests.requestBooks(...).then((data, response) => dispatch({action: 'books', data})),
                requests.requestAuthors(...).then((data, response) => dispatch({action: 'authors', data}))
            ])
            .then(() => dispatch({action: 'loaded-initial-data'}));
    };
}
```

I'll update it in the README. Thanks for catching that!

**Comment by jkosoy** [comment]
Yep, got that figured out! I was having trouble figuring out how to phrase my question though --

In `createActions` you specify a namespace as the first argument, but not in `createRequests`. Those should basically work the same way, right? Or is there a reason `createRequests` works differently?

🤔

**Comment by eugene-manuilov** [comment]
Actions, created by `createActions` function, fetch data from WordPress API and use `name` argument to trigger redux actions like `@@wp/${name}/fetching/${endpoint}` and `@@wp/${name}/fetched/${endpoint}`.

In the same time, requests created by `createRequests` function, just perform data fetch from WordPress API and don't generate redux actions. That is why we don't need `name` parameter for it.

**Comment by jkosoy** [comment]
Gotcha! Thanks for clarifying!
